title: Jiachen Project
subtitle: RISC-V Prosperity 2036

description: Towards unprecedented prosperity for the RISC-V ecosystem before 2036.

email: help@RV2036.org

baseurl: ""

url: "https://rv2036.org"

remote_theme: mmistakes/minimal-mistakes@4.27.3

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-polyglot

# 语言设置
languages: ["zh", "en"]
default_lang: "zh"
exclude_from_localizations: ["assets", "images", "css", "js"] # 这些资源不重复生成

parallel_localization: false # # Windows 不支持 fork，关闭并行构建
# permalink: /:lang/:path/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

logo: /assets/images/jiachen-logo-1x3.png

search: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/lazyparser"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rv2036"
    - label: "Forum"
      icon: "fab fa-fw fa-discourse"
      url: "https://forum.rv2036.org"
