title: Jiachen Project (甲辰计划)
description: Jiachen Project aims to realize a mature RISC-V’s ecosystem
  akin to the other mainstream ISAs by the next year of the Loong, 2036.
  This means mainstream-level maturity in applications such as datacenters,
  desktop computing, wearable technologies, and Internet of things - all
  implemented with systems of open standards and open source system software stacks.
# remote_theme: pages-themes/architect@v0.2.0

# email: your-email@example.com
baseurl: /
url: "https://rv2036.org"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#theme: minima
# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes@4.27.3
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache # Add this line

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

logo: /assets/images/jiachen-logo-1x3.png

search: true
